### ISSUE TITLE
裁剪上传完成之后再点击#fileapi就会报这个错 crop is not a function at Jquery.ImageCropUpload.js:45

### ISSUE THREAD

**Issue by apa7** [renyanwei/image-crop-upload#1]
你好, 你的这个插件帮了我的大忙, 十分感谢, 这个还维护吗, 留得接口简单易用, 挺好的,支持!

**Comment by apa7** [comment]
OK, 已解决, crop = crop(...) 这个函数, 然后crop.destroy()去掉

**Comment by renyanwei** [comment]
能够帮你很高兴。有时间的话一块来维护吧。
谢谢你的反馈，已经修复这个问题。
